/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { EventCreateDescription } from './eventCreateDescription';
import type { EventCreateRecurrenceRule } from './eventCreateRecurrenceRule';

export interface EventCreate {
  title: string;
  description: EventCreateDescription;
  location: string;
  start_time?: string;
  end_time: string;
  all_day?: boolean;
  recurrence_rule?: EventCreateRecurrenceRule;
}
