/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { EventPublicDescription } from './eventPublicDescription';
import type { EventPublicUpdatedAt } from './eventPublicUpdatedAt';
import type { EventPublicRecurrenceRule } from './eventPublicRecurrenceRule';
import type { EventPublicUpdatedBy } from './eventPublicUpdatedBy';

export interface EventPublic {
  title: string;
  description: EventPublicDescription;
  location: string;
  start_time?: string;
  end_time: string;
  all_day?: boolean;
  created_at?: string;
  updated_at?: EventPublicUpdatedAt;
  recurrence_rule?: EventPublicRecurrenceRule;
  created_by: string;
  updated_by?: EventPublicUpdatedBy;
  id: number;
}
