/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type EventRecurrence = typeof EventRecurrence[keyof typeof EventRecurrence];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventRecurrence = {
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
} as const;
