/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserLastLogin } from './userLastLogin';
import type { UserUserId } from './userUserId';

export interface User {
  username: string;
  first_name: string;
  last_name: string;
  created_at?: string;
  last_login: UserLastLogin;
  user_id?: UserUserId;
}
